-- DELETE ALL
DELETE FROM REVIEW_MARKS;
DELETE FROM REVIEWS;
ALTER TABLE REVIEWS ALTER COLUMN ID RESTART WITH 1;
DELETE FROM FRIENDSHIP_REQUESTS;
DELETE FROM LIKES;
DELETE FROM FILM_GENRE;
DELETE FROM USERS;
ALTER TABLE USERS ALTER COLUMN ID RESTART WITH 1;
DELETE FROM FILMS;
ALTER TABLE FILMS ALTER COLUMN ID RESTART WITH 1;
DELETE FROM GENRE;
ALTER TABLE GENRE ALTER COLUMN ID RESTART WITH 1;
DELETE FROM RATING;
ALTER TABLE RATING ALTER COLUMN ID RESTART WITH 1;
-- ADD GENRES
INSERT INTO GENRE (NAME) VALUES ('Комедия');
INSERT INTO GENRE (NAME) VALUES ('Драма');
INSERT INTO GENRE (NAME) VALUES ('Мультфильм');
INSERT INTO GENRE (NAME) VALUES ('Триллер');
INSERT INTO GENRE (NAME) VALUES ('Документальный');
INSERT INTO GENRE (NAME) VALUES ('Боевик');
-- ADD RATINGS
INSERT INTO RATING (NAME) VALUES ('G');
INSERT INTO RATING (NAME) VALUES ('PG');
INSERT INTO RATING (NAME) VALUES ('PG-13');
INSERT INTO RATING (NAME) VALUES ('R');
INSERT INTO RATING (NAME) VALUES ('NC-17');